name: Ruby

on:
  workflow_dispatch:
    inputs:
      version:
        description: "PaperAge release version (e.g. 1.2.3)"
        required: true

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true
    - name: Set up Homebrew
      run: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Update the formula
      run: "./bin/update_formula.rb ${{ github.event.inputs.version }}"
    - uses: EndBug/add-and-commit@v9
      with:
        add: "./Formula"
        default_author: github_actions
        message: "Update to PaperAge v${{ github.event.inputs.version }}"
        tag: "${{ github.event.inputs.version }}"
        push: false # Remove once done testing
